name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.1'

      - name: Build Package
        run: |
          corepack enable
          yarn install --immutable
          yarn build
          yarn workspace ipcman pack --filename ipcman.tgz
          mkdir -p build/dist
          mv packages/devtools/lib/index.js build/dist/ipcman.js
          mv packages/devtools-fe/build build/dist/build
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: ipcman-${{ github.sha }}
          path: ipcman.tgz

      - uses: actions/upload-artifact@v3
        with:
          name: ipcman-devtools-${{ github.sha }}
          path: build/dist
